### PR TITLE
allow the pari memory manager to be reset

### PR DESCRIPTION
**Pull request by fieker**
2nd attempt, the unwanted stuff is history

### CODE REVIEW

**Comment by wbhart** [comment]
But now Flint will allocate the memory internally using flint_malloc, but it will be freed by Julia with jl_free. Is this what we really want? Shouldn't we rather call flint_free directly to clean it up?

**Comment by fieker** [comment]
As far as I can see, we are using flint_free. IN the only case that I fixed (fmpz_get_str), I am actually calling flint_free (I thought)

Ahhhhhh, the quicksand of branches. Somewhere, I explicitly set the gmp-memory, the pari-memory and the flint-memory. And yes, we should call the flint_free (even if it currently will call jl_free)

**Comment by wbhart** [comment]
Yes, now _flint_free at least calls flint_free. However I don't see why it shouldn't call it directly instead of via an auxilliary function called _flint_free. 

Even if we do have this new auxilliary function it should be defined in the flint directory, not Nemo.jl I think. I guess it could go in FlintTypes.jl, though personally I'd just omit it.

Also, all the tests now fail because for some reason or other it can't find libpari after the changes you made. This is on OSX and Linux under both versions of Julia. So I suspect a real bug rather than a transient.

**Comment by fieker** [comment]
On Mon, Feb 29, 2016 at 07:49:41AM -0800, wbhart wrote:
> Yes, now _flint_free at least calls flint_free. However I don't see why it shouldn't call it directly instead of via an auxilliary function called _flint_free. 
> 
> Even if we do have this new auxilliary function it should be defined
> in the flint directory, not Nemo.jl I think. I guess it could go in
> FlintTypes.jl, though personally I'd just omit it.
I think it can get omitted. The reason it wsa there was more subtle: I
tried to install finalizers, but learned (the hard way) that ypui cannot
define finalizers for bit-types)
I'll see that I can get some more stuff to work now...
> 
> Also, all the tests now fail because for some reason or other it can't
> find libpari after the changes you made. This is on OSX and Linux
> under both versions of Julia. So I suspect a real bug rather than a
> transient.
Good!
that is the problem we discussed: if you build pari on the commandline,
it cannot find it. If you do it through Nemo, it works...
I am glad it happens to you as well!

**Comment by wbhart** [comment]
On 29 February 2016 at 17:50, fieker <notifications@github.com> wrote:

> On Mon, Feb 29, 2016 at 07:49:41AM -0800, wbhart wrote:
> > Yes, now _flint_free at least calls flint_free. However I don't see why
> it shouldn't call it directly instead of via an auxilliary function called
> _flint_free.
> >
> > Even if we do have this new auxilliary function it should be defined
> > in the flint directory, not Nemo.jl I think. I guess it could go in
> > FlintTypes.jl, though personally I'd just omit it.
> I think it can get omitted. The reason it wsa there was more subtle: I
> tried to install finalizers, but learned (the hard way) that ypui cannot
> define finalizers for bit-types)
> I'll see that I can get some more stuff to work now...
> >
> > Also, all the tests now fail because for some reason or other it can't
> > find libpari after the changes you made. This is on OSX and Linux
> > under both versions of Julia. So I suspect a real bug rather than a
> > transient.
> Good!
> that is the problem we discussed: if you build pari on the commandline,
> it cannot find it. If you do it through Nemo, it works...
> I am glad it happens to you as well!
>

No, I'm talking about the Travis CI tests. It builds everything from
scratch, including Pari, using the recipe in build.jl. I'm not just
rebuilding Pari on the command line.

Bill.

**Comment by wbhart** [comment]
However, this is possibly not your fault. It shows that tex is missing when trying to build Pari. Presumably Travis conveniently modified their setup again so it would break for us.

I thought we fixed this problem by removing make doc from the list of things we did for Pari. But apparently pari-2.7.4 tries to build the documentation when you do make install. Which leaves the question of why it ever worked before, since pari-2.7.4 hasn't changed (presumably).

**Pull request closed without merging**
