### PR TITLE
Add FqFiniteField constructor

### PR DESCRIPTION
**Pull request by thofma**
I have added another constructor for FqFiniteField using a given fmpz_mod_poly, similar to FqNmodFiniteField. I have added tests, do you also want documentation?

### CODE REVIEW

**Comment by wbhart** [comment]
Yes, we probably should have documentation for this. There's a couple of these factory methods that aren't documented I think, which is an oversight on my part. But we should be documenting them.

They'll be documented in the section before constructors, i.e. the general blurb at the beginning of the section. I think that is the best place to put them.

**Comment by thofma** [comment]
I have added documentation. Since I don't have a tex distribution here, I cannot test it.

**Comment by wbhart** [comment]
Thanks Tommy. Sorry this was pretty slow on my part. I've been heavily distracted this past week.

**Comment by wbhart** [comment]
I also just pushed some corrections, just to the tex.

**Pull request merged**
