### PR TITLE
Add _arb_set to improve reusability

### PR DESCRIPTION
**Pull request by thofma**
@fredrik-johansson 
I used some macro magic to provide non-exposed helper function(s)
```julia
_arb_set(x::arb, y::T)
_arb_set(x::Ptr{arb}, y::T)
_arb_set(x::arb, y::T, p::Int)
_arb_set(x::Ptr{arb}, y::T, p::Int)
```
where `T <: Union{Int, UInt, fmpz, fmpq, Float64, BigFloat64, AbstractString, arb}` (or a subset thereof), in arb.jl.
They will spare me from writing the same things over and over again. Using them I rewrote the arb constructors. I have added the pointer variant, so that when wrapping arb_mat I can do
```julia
setindex!(x::arb_mat, y::T, i::Int, j::Int)
  el = ccall((:arb_mat_entry, :libarb), ...) # el is of type Ptr{arb}
  _arb_set(el, y, prec(base_ring(x)))
end
```
and
```julia
function arb_mat(arr::Array{2, T}, p::Int)
  z = ccall((...))
  # for all entries do
    el = ccall((:arb_mat_entry, :libarb), ...)
    _arb_set(el, arr[i, j])
end
```
They could also help with the `setcoeff!(x::arb_poly, y::T, n::Int)` or constructors `arb_poly(Array{1, T})`.

If we agree that they are useful, I will add corresponding functions for acb.

P.S. I have also added a constructor `arb(::BigFloat)`.

### CODE REVIEW

**Comment by fredrik-johansson** [comment]
Good; we need some simplifications along these lines. I can't comment on whether this is the very best solution, but I have no objections either.

**Comment by wbhart** [comment]
I think we'll eventually be able to do these with traits. But there's no
point using Traits.jl just yet, as it is likely to be merged into the
language itself, possibly with some dedicated syntax.

For now, doing something like what you've done is probably the best we can
do.

Since Fredrik is happy I'm inclined to just merge this.

Bill.

**Comment by wbhart** [comment]
Where is arb_mid_ptr? It doesn't seem to be in Arb.

**Comment by wbhart** [comment]
My mistake, I was pulling from Tommy's arb repo by mistake.

**Pull request merged**
