### PR TITLE
remove sum/prod for arrays of fmpz. Julia is already better there

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by wbhart** [comment]
This commit doesn't seem to apply to my master. In fact it seems to be a revert of your changes rather than a commit, so I can't actually commit it.

**Comment by fieker** [comment]
On Thu, Feb 11, 2016 at 03:01:40AM -0800, wbhart wrote:
> This commit doesn't seem to apply to my master. In fact it seems to be a revert of your changes rather than a commit, so I can't actually commit it.
> 
> ---

I really like git...

Strange: the diff I see on github looks correct: I basically indented
all the fmpz-array stuff (both functions) and added a comment.
This is reflected in the diff...

I can try to somplify and just remove the block of code?

**Comment by wbhart** [comment]
Sorry, I'm using the mobile GitHub interface and hence misread the conflict warning and the commit. All is fine, I will merge immediately.

**Comment by fieker** [comment]
On Thu, Feb 11, 2016 at 03:24:09AM -0800, wbhart wrote:
> Sorry, I'm using the mobile GitHub interface and hence misread the conflict warning and the commit. All is fine, I will merge immediately.
> 
No worries and no hurry. I just though this is actually quite cute and
good for julia.

PS.: my version is still better...

PPS.: I have a branch that runs under 0.5 - the latest. The changes are
actually minimal:

for T in subtypes(PolyElem)
  (f::T)(a) = subst(f, a)

  function (f::T)(a::T)
     if parent(f) != parent(a)
        return subst(f, a)
     end
     return compose(f, a)
  end

  (f::T)(a::Integer) = evaluate(f, a)
  (f::T)(a::fmpz) = evaluate(f, a)


  function (f::T)(a::RingElem)
     if parent(a) != base_ring(f)
        return subst(f, a)
     end
     return evaluate(f, a)
  end

end

**Comment by wbhart** [comment]
After pressing "Merge pull request" over 100 times after various reloads, I gave up trying to merge it with the mobile interface.

Now I have a real computer.

**Comment by fieker** [comment]
On Thu, Feb 11, 2016 at 04:21:35AM -0800, wbhart wrote:
> After pressing "Merge pull request" over 100 times after various reloads, I gave up trying to merge it with the mobile interface.
> 
> Now I have a real computer.
> 
Ain't it fun?

**Pull request merged**
