### PR TITLE
Randomized tests for generic polynomials (evalution -> end)

### PR DESCRIPTION
**Pull request by defeo**
Random failures for

- composition,
- gcdx,
- generic_eval (likely the same problem as for composition).

Interpolation always fails.

### CODE REVIEW

**Comment by wbhart** [comment]
I think you need some for loops to test lots of randomly generated polynomials, not just one randomly generated example.

**Comment by wbhart** [comment]
There is a trailing comment on one of the lines, which can be removed. It reads # || (f, g, h)

Also note that the current code doesn't test both branches of the composition function. It does something different for polynomials of sufficient length.

**Comment by wbhart** [comment]
I am unable to get your gcdx tests to fail. You may need to give an example of this behaviour.

Also note there are multiple different versions of gcdx. Testing only for Z[x][y] won't test all versions of the function.

**Comment by wbhart** [comment]
The integral test seems to be failing because the rand function is being called incorrectly.

**Comment by thofma** [comment]
Wrong repository?

**Comment by wbhart** [comment]
No, we are working on a branch in my repo.

**Comment by defeo** [comment]
- Funny: integral was passing last time I commited. I wonder how!
- I only see 2 versions of gcdx. Are there more?
- I can't seem to reproduce faulty gcdx either.

**Pull request merged**
