### PR TITLE
allow nmod mat with zero rows/cols

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by wbhart** [comment]
Shouldn't we change the error messages too so they say "dimensions must be non-negative"? Or am I misreading the commit again.

Also, I don't know if this is supported by Flint or not. Should we not change the test functions to test these cases?

**Comment by wbhart** [comment]
OK, I checked and the only Flint functions that are not tested for size zero matrices are howell_form and window_init/clear, both likely because the contributors didn't know Flint supported such matrices. So we either need to fix this in Flint or add checks for such cases in Nemo.

I don't think we use Windows in Nemo anyway, so that only leaves Howell form.

**Comment by thofma** [comment]
I will change it for the Howell form in flint.

**Comment by wbhart** [comment]
Thanks. When done could you add a comment to this effect to the Flint issue I just opened.

**Comment by fieker** [comment]
On Mon, Feb 15, 2016 at 11:37:33PM -0800, wbhart wrote:
> OK, I checked and the only Flint functions that are not tested for size zero matrices are howell_form and window_init/clear, both likely because the contributors didn't know Flint supported such matrices. So we either need to fix this in Flint or add checks for such cases in Nemo.
> 
> I don't think we use Windows in Nemo anyway, so that only leaves Howell form.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/wbhart/Nemo.jl/pull/33#issuecomment-184560924

I think this should fully supported - I stumbled across this by doing
A = matrix with 0 rows over Z/pZ
B = matrix with 1 row

then matrix B gets repeatedly vcat'ed to A. Nemo complained since A
turned out to be a generic matrix, while B was nmod_mat

After removing the check for 0, all was fine. The 0 row/col matrices are
important for the interface, they remove the need to always have special
code for the corner cases in all applications. It is (I think) more
efficient to deal with this centrally rather than everywhere...

**Comment by wbhart** [comment]
Yes, I agree. It's only a matter of ensuring that Flint really does support
it. We might have the same issue with some of the other matrix modules.

**Comment by thofma** [comment]
I adjusted the error messages.

**Pull request merged**
