### PR TITLE
Type inference

### PR DESCRIPTION
**Pull request by thofma**
I define `parent_type(::Type{T})` for all types of ring elements, e.g. `parent_type(::Type{fmpz}) = FlintIntegerRing`. Then the `base_ring` function looks like this:
```julia
base_ring(R::MatrixSpace{T}) = R.base_ring::parent_type(R)
```
This fixes almost all type stability problems.

I also made the parent object constructors type stable.

### CODE REVIEW

**Comment by wbhart** [comment]
Thanks for this pretty impressive patch! I'm not seeing Travis again, so don't know if this passes or not.

I asked about our Travis failure on julia-users and the opinion seems to be it is a bug somewhere in Nemo, probably in a ccall, that is forgiven intermittently by the gc.

**Comment by thofma** [comment]
We should wait for travis.

**Comment by wbhart** [comment]
Will it turn up eventually.

**Comment by wbhart** [comment]
I don't know if you can see this, but this PR is not listed in the Travis list:

https://travis-ci.org/wbhart/Nemo.jl/pull_requests

**Comment by thofma** [comment]
I see it. The error for the build
https://travis-ci.org/wbhart/Nemo.jl/builds/111189162
is also interesting. He tried to apply #41, which of course did not exist anymore. I don't know if this confused him completely to the point that he won't check any pull request.

**Comment by thofma** [comment]
Ok, he is building the pull request #43. I guess I will close this one and open it again.

**Comment by wbhart** [comment]
Yes, that seemed to trigger it. I see it now.

Claus' PR started testing right away it seems.

**Comment by wbhart** [comment]
And this one passes!

**Pull request merged**
