### PR TITLE
some more unsafe stuff for fmpz, num() for nf_elem

### PR DESCRIPTION
**Pull request by fieker**

### CODE REVIEW

**Comment by thofma** [comment]
The travis error is strange.

**Comment by wbhart** [comment]
I don't think setting copy to deepcopy is the right thing to do. They serve different purposes.

**Comment by wbhart** [comment]
I think these should be two separate pull requests as they are unrelated from a Nemo point of view.

I'm not at all convinced that we want to add more and more unsafe functions. I think there is a case for having sub! and neg! maybe, but if code really depends on having C like semantics for divexact and gcd then I would argue that we should consider moving the relevant code to C.

There's little use in having a high level language and then using it everywhere the same way that we use C.

I certainly don't want to add divexact! and gcd! for every ring in Nemo!

**Comment by wbhart** [comment]
Actually, I mean that it might be worth having subeq! not sub!. I was already bothered by having add! the other day.

The thing that should decide for us is whether we frequently call the function in a loop. In the case of addeq! we do call it in a loop for example in matrix code, and the performance depends critically on this. We really have a single object that we are trying to update repeatedly.

I can't think of any case where divexact or gcd would be called repeatedly in such a tight, performance critical loop. I guess content would be one place in the case of gcd. But such functions should definitely be in C, not Julia!

**Comment by fieker** [comment]
It's your project, thus your rules.

My approach is slightly different, while I do not mind having muleq,
addeq, ... and thus in, quite likely also with the additional api of
returning the result, I don't see the downside of allowing stuff in
julia. In fact, I am calling flint-library functions whenever I need
the functionality...

Sure, some of if would be better of in c, but it is mostly not going to
happen: there is a lot of (mental) overhead involed, like designing a
build system, testing on all architectures, ....
A lot of the stuff will not be of interest to antic or flint, it is only
a small bit of tight loop to be used from julia.
I can (and will) just put the missing unsafe operations in Hecke, no
worries.
It it turns out that s.th. is easier in c, we will do it, but I'd like
to keep Hecke as c-free as possible as to not have the hazzle of haing
to worry about building c bits.
Julia has this waxed, so I intend to use it as much as possible.

To put it in the different direction: what is the downside of doing
c-style coding in julia?
I should get the full performance
without hazzles of the c-development model
It is much more user-transparent (as (s)he can see the code and easily
  change it...

Greetings
 Claus

All I can see is that the Julia functio will look ugly...

**Comment by fieker** [comment]
On Tue, Feb 23, 2016 at 08:00:58AM -0800, wbhart wrote:
> I don't think setting copy to deepcopy is the right thing to do. They serve different purposes.
> 
Well, then we should provide copy for all data types. It is, as a use,
frutrating if I have to guess weather copy or deepcopy is available. For
things like fmpz they are the same. For fmpz_poly, we (you) might decide
to separate them into different functions, but they should both be
defined.

**Comment by fieker** [comment]
On Tue, Feb 23, 2016 at 08:07:59AM -0800, wbhart wrote:
> I think these should be two separate pull requests as they are unrelated from a Nemo point of view.
> 
Yep - they are 2 commits. The problem is to convince github to split
them...
> I'm not at all convinced that we want to add more and more unsafe
> functions. I think there is a case for having sub! and neg! maybe, but
> if code really depends on having C like semantics for divexact and gcd
> then I would argue that we should consider moving the relevant code to
> C.
I am happy to have finished, time critical stuff in c, but realisticly,
this is not going to happen. Most of the time critical stuff is just not
intersting as a stand-alone function for antic/ flint, it is only
meaningful as a small step for a larger system (Nemo/ Hecke). As such, I
don't know where in the source-tree it should go. This would seem to
neccessitate starting a new librariy, call it Nemo-Hecke-helpers. I
don't think this is going to be very successful...
> 
> There's little use in having a high level language and then using it
> everywhere the same way that we use C.
Not everywhere, but where needed. We have plenty of very high-level
stuff, but need to have some low-level stuff as well...
> 
> I certainly don't want to add divexact! and gcd! for every ring in Nemo!
Why? What is the downside?

As I said before, I'll but them in Hecke/Misc somewhere...

**Comment by wbhart** [comment]
OK, just to summarise, since we've discussed privately. My main reasons for
being worried about more unsafe operators are:

1) They really are unsafe, and a pain to debug if accidentally used
incorrectly.

2) If we implement them for one module then we'll drive our users and
developers insane if we don't implement them for all modules, and this is a
large amount of work.

3) I am still not convinced they have enough applications in the case of
divexact or gcd, which are already pretty expensive computations.

4) At some point we have to change the interface of all unsafe operators to
return their return values. The more complex we make the existing unsafe
operator interface, the more work we'll have to do later to fix them.

5) They exist to solve a problem that I am not sure should exist in the
long run, namely the cost of short term garbage collection, which basically
should be almost free with generational collection. We aren't yet using
Julia sufficiently correctly and consistently to judge whether this is a
problem we need to solve.

I don't think of Nemo as my project and my rules, but a collaboration. For
the time being my comment for consideration is that I think we should hold
off on including more unsafe operators. I may even like to remove some of
them, such as the scattered add! and sub!'s that we have, and just support
addeq!, subeq! (maybe) and mul! for now. It makes documentation easier, and
maintenance, at least until we can characterise the issues with the gc more
carefully.

Setting copy to deepcopy for Flint objects doesn't make sense since copy
means shallow copy in Julia, and Flint doesn't currently implement that
(except for matrix windows I guess, which could be viewed as a kind of
shallow copy). We could implement shallow copy in Flint I guess. But this
is again typically unsafe for Flint style objects. I'm not convinced it's
good practice. I'm happy to consider any potential applications as they
arise, obviously. We should look at where Julia actually uses copy vs
deepcopy to make sure that whatever semantics we support don't lead to
broken collections of Flint objects in Julia. For obvious reasons it's hard
to get this right at present.

Bill.

**Pull request closed without merging**
