### PR TITLE
Benchmarks

### PR DESCRIPTION
**Pull request by thofma**
Do you want this in the git branch?

### CODE REVIEW

**Comment by wbhart** [comment]
Sure, why not.

**Comment by thofma** [comment]
Where to put in the directory tree?

**Comment by wbhart** [comment]
Maybe a directory called benchmarks. Would that work?

**Comment by wbhart** [comment]
I think it would be better if each of the benchmarks was in a different file. Then we can just link them individually from the website.

**Comment by wbhart** [comment]
Also I guess it would be useful if each benchmark returned the time of the final command, i.e. @time blah

**Comment by thofma** [comment]
Changed it.

**Comment by thofma** [comment]
julia> Nemo.benchmark_all()
benchmark_fateman ... 1.625590156
benchmark_pearce ... 0.576332748
benchmark_resultant ... 0.113175366
benchmark_poly_nf_elem ... 0.079148769
benchmark_solve_poly ... 4.544049345
benchmark_znz_det ... 6.542204953
benchmark_nf_det ... 1.61097438
benchmark_bernoulli ... 49.319393877
benchmark_det_poly_ring ... 0.15354214
benchmark_charpoly_int ... 0.026699641
benchmark_minpoly_gcd_domain ... 6.127203208
benchmark_minpoly_finite_field ... 0.080272466
benchmark_minpoly_integers ... 0.01556747

**Comment by wbhart** [comment]
Nice. Thank you!

**Pull request merged**
